version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ~/develop/docker-volumes/flowup-middle-data/postgresql/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      PATH_TO_STORAGE: /var/lib/postgresql/data/